### ISSUE TITLE
Undefined function :swab.sync/2

### ISSUE THREAD

**Issue by mjc** [johnhamelink/exrm-deb#19]
```
==> Failed to execute after_release hook for Elixir.ReleaseManager.Plugin.Deb!
** (UndefinedFunctionError) undefined function :swab.sync/2 (module :swab is not available)
:swab.sync([convert: :gunzip, tar: :fakeroot, convert: :gzip], <<31, 139, 8, [..snip..]>>
   lib/exrm_deb/utils/compression.ex:36: ExrmDeb.Utils.Compression.compress/3
    lib/exrm_deb/data.ex:20: ExrmDeb.Data.build/2
    lib/exrm_deb.ex:26: ReleaseManager.Plugin.Deb.start_build/1
    lib/mix/tasks/release.ex:262: anonymous fn/2 in Mix.Tasks.Release.execute_after_hooks/1
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/release.ex:80: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by mjc** [comment]
On debian jessie in a docker container. Ubuntu 14.04.4 LTS server also does the same thing.

**Comment by johnhamelink** [comment]
@mjc could you share the docker container so I can try to replicate?

**Comment by mjc** [comment]
@johnhamelink it's `FROM elixir:1.2` with `postgresql-client-9.4` and `git` added

**Comment by johnhamelink** [comment]
@mjc I'm away on holiday tomorrow for a week, sorry but I'll have to take a look at it after then! (Where I'm going there will be no electricity!)

**Comment by mjc** [comment]
I was able to resolve this by adding swab to my project's dependencies and application list.  Running into other issues now
