### ISSUE TITLE
Failed to execute after_release hook for Elixir.ReleaseManager.Plugin.Deb

### ISSUE THREAD

**Issue by niku** [johnhamelink/exrm-deb#6]
I ran into error when I executed `exrm release --deb` in my sandbox.
Here is a log:

```
src$ cat /etc/debian_version
8.3

src$ uname -a
Linux packer-virtualbox-iso-1457657143 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

src$ elixir -v
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [async-threads:10] [kernel-poll:false]

Elixir 1.2.3

src$ mix -v
Mix 1.2.3

src$ mix new --sup exrm_deb_sandbox
* creating README.md
* creating .gitignore
* creating mix.exs
* creating config
* creating config/config.exs
* creating lib
* creating lib/exrm_deb_sandbox.ex
* creating test
* creating test/test_helper.exs
* creating test/exrm_deb_sandbox_test.exs

Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:

    cd exrm_deb_sandbox
    mix test

Run "mix help" for more commands.

src$ cd exrm_deb_sandbox/

src/exrm_deb_sandbox$  git init && git add . && git commit -am "First Import"

src/exrm_deb_sandbox$ (...edit mix.exs...)

src/exrm_deb_sandbox$ git show
commit b6e5ed019ea196358d37baaa2443e7358ce6a64b
Author: niku <niku@niku.name>
Date:   Mon Mar 14 20:11:28 2016 +0900

    Use exrm_deb

diff --git a/mix.exs b/mix.exs
index 6ee8bb4..246a39b 100644
--- a/mix.exs
+++ b/mix.exs
@@ -7,14 +7,16 @@ defmodule ExrmDebSandbox.Mixfile do
      elixir: "~> 1.2",
      build_embedded: Mix.env == :prod,
      start_permanent: Mix.env == :prod,
-     deps: deps]
+     deps: deps,
+     description: "A sandbox of exrm_deb",
+     package: package]
   end

   # Configuration for the OTP application
   #
   # Type "mix help compile.app" for more information
   def application do
-    [applications: [:logger],
+    [applications: [:logger, :exrm_deb],
      mod: {ExrmDebSandbox, []}]
   end

@@ -28,6 +30,20 @@ defmodule ExrmDebSandbox.Mixfile do
   #
   # Type "mix help deps" for more examples and options
   defp deps do
-    []
+    [{:exrm_deb, "0.0.4"}]
+  end
+
+  defp package do
+    [
+      external_dependencies: [],
+      license_file: "LICENSE",
+      maintainers: ["niku <niku@niku.name>"],
+      licenses: ["MIT"],
+      vendor: "niku",
+      links:  %{
+        "GitHub" => "https://github.com/niku/exrm_deb_sandbox",
+        "Homepage" => "https://github.com/niku/exrm_deb_sandbox"
+      }
+    ]
   end
 end

src/exrm_deb_sandbox$ mix do deps.get, release --deb
(...snip...)
==> exrm_deb
Compiled lib/exrm_deb.ex
Compiled lib/exrm_deb/control.ex
Compiled lib/exrm_deb/data.ex
Compiled lib/exrm_deb/deb.ex
Compiled lib/exrm_deb/generators/changelog.ex
Compiled lib/exrm_deb/config.ex
Compiled lib/exrm_deb/generators/control.ex
Compiled lib/exrm_deb/generators/systemd.ex
Compiled lib/exrm_deb/generators/template_finder.ex
Compiled lib/exrm_deb/generators/upstart.ex
Compiled lib/exrm_deb/utils/compression.ex
Compiled lib/exrm_deb/utils/config.ex
Compiled lib/exrm_deb/utils/file.ex
lib/mix/tasks/release.deb.generate_templates.ex:25: warning: variable source is unused
Compiled lib/mix/tasks/release.deb.generate_templates.ex
Generated exrm_deb app
==> exrm_deb_sandbox
Compiled lib/exrm_deb_sandbox.ex
Generated exrm_deb_sandbox app
Consolidated Timex.Date.Convert
Consolidated Vex.Validator.Source
Consolidated Vex.Extract
Consolidated Vex.Blank
Consolidated List.Chars
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
Building release with MIX_ENV=dev.
==> Failed to execute after_release hook for Elixir.ReleaseManager.Plugin.Deb!
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:346: IO.chardata_to_string(nil)
    (elixir) lib/path.ex:467: Path.join/2
    (elixir) lib/path.ex:449: Path.join/1
    lib/exrm_deb/generators/changelog.ex:14: ExrmDeb.Generators.Changelog.build/2
    lib/exrm_deb/data.ex:10: ExrmDeb.Data.build/2
    lib/exrm_deb.ex:26: ReleaseManager.Plugin.Deb.start_build/1
    lib/mix/tasks/release.ex:262: anonymous fn/2 in Mix.Tasks.Release.execute_after_hooks/1
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3

src/exrm_deb_sandbox$ cat mix.lock 
%{"bbmustache": {:hex, :bbmustache, "1.0.4"},
  "certifi": {:hex, :certifi, "0.4.0"},
  "cf": {:hex, :cf, "0.2.1"},
  "combine": {:hex, :combine, "0.7.0"},
  "earmark": {:hex, :earmark, "0.2.1"},
  "erlware_commons": {:hex, :erlware_commons, "0.19.0"},
  "ex_doc": {:hex, :ex_doc, "0.11.4"},
  "exrm": {:hex, :exrm, "1.0.2"},
  "exrm_deb": {:hex, :exrm_deb, "0.0.4"},
  "getopt": {:hex, :getopt, "0.8.2"},
  "hackney": {:hex, :hackney, "1.5.1"},
  "idna": {:hex, :idna, "1.1.0"},
  "metrics": {:hex, :metrics, "1.0.1"},
  "mimerl": {:hex, :mimerl, "1.0.2"},
  "providers": {:hex, :providers, "1.6.0"},
  "relx": {:hex, :relx, "3.18.0"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.6"},
  "timex": {:hex, :timex, "1.0.2"},
  "tzdata": {:hex, :tzdata, "0.5.6"},
  "vex": {:hex, :vex, "0.5.5"}}
```

**Comment by johnhamelink** [comment]
Hey @niku, thanks for this detailed issue. I'll take a look and see what this issue is later on today.

Thanks again!

**Comment by niku** [comment]
Hi, I'm digging deeper.

I rewrite `ExrmDeb.Utils.root` to:

``` ex
  def root do
    IO.inspect "** Application.get_all_env(:exrm_deb) => #{inspect Application.get_all_env(:exrm_deb)} **"
    IO.inspect "** Application.get_env(:exrm_deb, :root) => #{inspect Application.get_env(:exrm_deb, :root)} **"
    Application.get_env(:exrm_deb, :root)
  end
```

And, I execute `mix do release --deb` again.

```
"** Application.get_all_env(:exrm_deb) => [] **"
"** Application.get_env(:exrm_deb, :root) => nil **"
```

It seems `ExrmDeb.Utils.Config.root` returns `nil` in the above environment.
But I'm not sure why it returns nil :cry: 

Hope it helps.

**Comment by johnhamelink** [comment]
@niku I believe it's fixed now, give it a shot!

``` elixir
{:exrm_deb, github: "johnhamelink/exrm_deb", ref: "5d09389"}
```

If it works, let me know and I'll release a new hex package.

Thanks!

**Comment by johnhamelink** [comment]
@niku did you get a chance to check that this works for you?

**Comment by niku** [comment]
Sorry for the reply.

A release command is succeed.
So, I think this issue is closable.Thank you!

```
% mix do deps.get, release --deb
(...snip...)
Building release with MIX_ENV=dev.
==> A debian package has successfully been created. You can find it in the ./rel directory
==> The release for exrm_deb_sandbox-0.0.1 is ready!
==> You can boot a console running your release with `$ rel/exrm_deb_sandbox/bin/exrm_deb_sandbox console`
```

Unfortunately, I ran into other issue #9.
I think better that we would wait release until fixing the issue.
